// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBthS-OVlFbWwc9Wz_uscVlnH2bR12q1h0',
    appId: '1:354527235548:web:99cf284630c8a2b62e1319',
    messagingSenderId: '354527235548',
    projectId: 'apptest-13f95',
    authDomain: 'apptest-13f95.firebaseapp.com',
    storageBucket: 'apptest-13f95.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDVXk75NNaHCydnyWjf8h9uwd0GJMFEXk',
    appId: '1:354527235548:android:8906117f46aa4e162e1319',
    messagingSenderId: '354527235548',
    projectId: 'apptest-13f95',
    storageBucket: 'apptest-13f95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLYll_TzWVJtb_NcTGPTfO_2eiEVV41ns',
    appId: '1:354527235548:ios:a76870964e1ed2f92e1319',
    messagingSenderId: '354527235548',
    projectId: 'apptest-13f95',
    storageBucket: 'apptest-13f95.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLYll_TzWVJtb_NcTGPTfO_2eiEVV41ns',
    appId: '1:354527235548:ios:25d902b61f9305b32e1319',
    messagingSenderId: '354527235548',
    projectId: 'apptest-13f95',
    storageBucket: 'apptest-13f95.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
